apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: redis
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'registry-1.docker.io/bitnamicharts'  # OCI-источник!
    chart: redis
    targetRevision: 20.0.5 
    helm:
      parameters:
        - name: global.redis.password
          value: 'karat1st'
        - name: pdb.create
          value: 'true'
        - name: replica.replicaCount
          value: '1'
        - name: master.persistence.enabled
          value: 'true'
        - name: master.config.appendonly
          value: 'no'
          
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: redis
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true