---
- name: Check if kubeadm has already run
  ansible.builtin.stat:
    path: "/etc/kubernetes/pki/ca.key"
  register: kubeadm_ca

# Подставляем переменные полученные в файле prepare.yaml
- name: Join control nodes
  when: not kubeadm_ca.stat.exists
  ansible.builtin.command:
    cmd: >
      kubeadm join {{ hostvars[groups['k8s_masters'][0]].join_path.stdout }}
      --token {{ hostvars[groups['k8s_masters'][0]].join_token.stdout }}
      --discovery-token-ca-cert-hash sha256:{{ hostvars[groups['k8s_masters'][0]].discovery_token_ca_cert_hash.stdout }}
      --control-plane --certificate-key {{ hostvars[groups['k8s_masters'][0]].certificate_key.stdout }}
      --apiserver-advertise-address {{ ansible_host }}
  register: kubeadm_join
  changed_when: kubeadm_join.rc != 0

# Add link

- name: Add directory for config file
  ansible.builtin.file:
    path: /root/.kube
    state: directory
    mode: "0700"

- name: Add link for config file
  ansible.builtin.file:
    src: /etc/kubernetes/admin.conf
    dest: /root/.kube/config
    state: link

- name: Kubelet enable
  ansible.builtin.service:
    name: kubelet
    state: started
    enabled: true
