- name: Init master control node
  ansible.builtin.command: kubeadm init --config /etc/kubernetes/kubeadm-config.yaml
  register: kubeadm_init
  changed_when: kubeadm_init.rc != 0

- name: Install Utils
  ansible.builtin.include_tasks: utils.yaml

- name: Check for installed tigera-operator
  ansible.builtin.command: kubectl get ns tigera-operator
  register: tigera_operator_out
  changed_when: tigera_operator_out.rc != 0
  ignore_errors: true

- name: Install tigera-operator
  when: tigera_operator_out.rc == 1
  ansible.builtin.command: "kubectl create -f {{ tigera_operator_github_url }}{{ tigera_operator_version }}/manifests/tigera-operator.yaml"
  register: kubectl_create_tigera_operator
  changed_when: kubectl_create_tigera_operator.rc != 0

- name: Copy calico-install.yaml
  ansible.builtin.template:
    src: calico-install.j2
    dest: /etc/kubernetes/calico-install.yaml
    mode: "0600"

- name: Install Calico
  ansible.builtin.command: kubectl apply -f /etc/kubernetes/calico-install.yaml
  register: kubectl_apply_calico_install
  changed_when: kubectl_apply_calico_install.rc != 0
