---
- name: Check if kubeadm has already run
  ansible.builtin.stat:
    path: "/etc/kubernetes/pki/ca.key"
  register: kubeadm_ca

- name: Stop install master
  when: kubeadm_ca.stat.exists
  block:
    - name: End play if 1-st control already run
      ansible.builtin.debug:
        msg: "Master alreeady run. File /etc/kubernetes/pki/ca.key exist."
    - name: End play
      ansible.builtin.meta: end_play

- name: Create /etc/kubernetes directory
  ansible.builtin.file:
    path: /etc/kubernetes
    state: directory
    mode: '0700'

- name: Copy kubeadm-config.yaml
  ansible.builtin.template:
    src: kubeadm-config.j2
    dest: /etc/kubernetes/kubeadm-config.yaml
    mode: '0600'

- name: Load k8s containers
  ansible.builtin.command: kubeadm config images pull
  register: kubeadm_images_pull
  changed_when: kubeadm_images_pull.rc != 0

- name: Calico
  when: cni == 'calico'
  block:

    - name: Install Calico
      when: enableBPF is not defined
      ansible.builtin.include_tasks: calico.yaml

    - name: Install Calico with BPF
      when: enableBPF is defined
      ansible.builtin.include_tasks: calico-bpf.yaml

    - name: Install Calicoctl
      ansible.builtin.get_url:
        url: "{{ calicoctl_url }}{{ tigera_operator_version }}/calicoctl-linux-amd64"
        dest: /usr/local/bin/calicoctl
        mode: '0755'

- name: Flannel
  when: cni == 'flannel'
  ansible.builtin.include_tasks: flannel.yaml

- name: Setup DNS
  ansible.builtin.include_tasks: dns.yaml

- name: Kubelet enable
  ansible.builtin.service:
    name: kubelet
    state: started
    enabled: true

### Helm
- name: Helm install
  when: helmVersion is defined
  block:
    - name: "Install Helm"
      ansible.builtin.unarchive:
        src: "https://get.helm.sh/helm-{{ helmVersion }}-linux-amd64.tar.gz"
        dest: /root/
        remote_src: true
        creates: /root/linux-amd64
      register: helm

    - name: Move helm in /usr/local/sbin # noqa: no-handler
      ansible.builtin.command: mv /root/linux-amd64/helm /usr/local/sbin/helm
      when: helm.changed
      register: move_helm
      changed_when: move_helm.rc != 0

    - name: Check is helm-diff plugin installed
      ansible.builtin.shell:
        cmd: |
          /usr/local/sbin/helm plugin list | grep -q diff
      register: helm_diff
      ignore_errors: true
      changed_when: helm_diff.rc != 0

    - name: "Helm, install plugin helm-diff"
      ansible.builtin.command: /usr/local/sbin/helm plugin install https://github.com/databus23/helm-diff
      when: helm_diff.rc != 0
      register: helm_plugin
      changed_when: helm_plugin.rc != 0
